# Generated by Django 5.0.2 on 2024-02-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_estacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dato',
            old_name='hum_suelo',
            new_name='HA',
        ),
        migrations.RenameField(
            model_name='dato',
            old_name='humedad',
            new_name='HS',
        ),
        migrations.RenameField(
            model_name='dato',
            old_name='temp_suelo',
            new_name='TA',
        ),
        migrations.RenameField(
            model_name='dato',
            old_name='temperatura',
            new_name='TS',
        ),
    ]
